config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create,:destroy]
  resources :friendships, only: [:create,:destroy]
  devise_for :users
  get 'welcome/index'
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  get 'chart', to: 'stocks#chart'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  validates :name, :ticker, presence: true
  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
        publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
        endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      new(ticker: ticker_symbol,name:client.company(ticker_symbol).company_name,last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end
  def self.chart(ticker_symbol)
    client = IEX::Api::Client.new(
        publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
        endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      #new(ticker: ticker_symbol,name:client.company(ticker_symbol).company_name,last_price: client.price(ticker_symbol))
      client.chart(ticker_symbol)
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
 has_many :user_stocks
 has_many :stocks, through:  :user_stocks
 has_many :friendships
 has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def under_stock_limit?
	  stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
	  under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def stock_already_tracked?(ticker_symbol)
   stock = Stock.check_db(ticker_symbol)
   return false unless stock
   stocks.where(id: stock.id).exists?
  end
  def full_name
   return  "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end
 def self.search(param)
  param.strip!
  to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
  return nil unless to_send_back
  to_send_back
 end

 def self.first_name_matches(param)
  matches('first_name',param)
 end
 def self.last_name_matches(param)
  matches('last_name',param)
 end

 def self.email_matches(param)
  matches("email",param)
 end

 def self.matches(field_name, param)
  where("#{field_name} like ?", "%#{param}%")
 end

 def except_current_user(users)
  users.reject { |user| user.id == self.id }
 end

 def not_friends_with?(id_to_friend)
  !self.friends.where(id:id_to_friend).exists?
 end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @article = Article.new
  end
  def edit
    @article = Article.find(params[:id])
  end
  def show
    @article = Article.find(params[:id])
  end
  def index
    @articles = Article.all
  end
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  private
    def article_params
      params.require(:article).permit(:title,:text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
  private
  def comment_params
    params.require(:comment).permit(:commenter,:body)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
  end

  def destory
    friendship = current_user.friendships.where(friend_id: params[:id])
    friendship.destroy
    flash[:notice] = "Stopped following"
    redirect_to my_friend_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |fm|
          fm.js {render partial: 'users/result'}
        end
      else
        flash.now[:alert] = "Please enter a valid symbol to search"
        respond_to do |fm|
          fm.js {render partial: 'users/result'}
        end
      end
    else
      flash.now[:alert] = "Please enter a symbol to search"
      respond_to do |fm|
        fm.js {render partial: 'users/result'}
      end
    end
  end
  def chart
    if params[:stock].present?
      @stock = Stock.chart(params[:stock])
      if @stock
        render json: @stock
      else
        flash[:alert] = "Please enter a valid symbol to search"
        redirect_to my_portfolio_path
      end
    else
      flash[:alert] = "Please enter a symbol to search"
      redirect_to my_portfolio_path
    end

  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save!
    end
    @user_stock = UserStock.create(user: current_user,stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added into your  portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice]  = "#{stock.name} was successfully removed from your portfolio "
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
  end
  def my_friends
    @friends = current_user.friends
  end
  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |fm|
          fm.js {render partial: 'users/friend_result'}
        end
      else
        respond_to do |fm|
          flash.now[:alert] = "Couldn't find user"
          fm.js {render partial: 'users/friend_result'}
        end
      end
    else
      respond_to do |fm|
        flash.now[:alert] = "Please enter a friend to name or email to search"
        fm.js {render partial: 'users/friend_result'}
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1> Edit Article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h> Listing Articles</h>
<table>
  <%= link_to 'New article', new_article_path %>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
    <th></th>
  </tr>
  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Show',article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article_path(article),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/from' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete, data: {confirm: "Are you sure?"} %>
</p>

app/views/comments/_from.html.erb
<%= form_with(model: [@article,@article.comments.build],local: true) do |form|%>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%=form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<%end%>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th scope="col">Ticker</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @tracked_stocks.each do |stock| %>
        <tr>
          <th scope="row"><%= stock.ticker %></th>
          <td><%= stock.name %></td>
          <td><%= stock.last_price %></td>
          <td><%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure ?'},
                                          class: 'btn btn-sm btn-warning' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @friends %>
  <div class="card card-header results-block">
    <table class="col-md-12">
      <tbody>
          <% @friends.each  do |friend| %>
            <tr>
              <td><strong>Name: </strong> <%= friend.full_name %></td>
              <td><strong>Email: </strong> <%= friend.email %> </td>
              <td><strong>Profile: </strong> <%= link_to "View Profile", '#',
                                                   class: "btn btn-sm btn-sucess"%>
                <% if current_user.not_friends_with?(friend.id) %>
                  <%= link_to "Follow friend?", '#',
                        class: "btn btn-sm btn-success", method: :post %>
                <% else %>
                  <span class="badge badge-secondary">
                    You are friends
                  </span>
                <% end %>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user,ticker: @stock.ticker),
                                   class: "btn btn-xs btn-success", method: :post %>
    <% else %>
      <span class="badge badge-secondary">
         you already tracking
        <% if !current_user.under_stock_limit? %>
           10 stocks
        <% end %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<%end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/my_friends.html.erb
<h1>Friends</h1>
<div class='search-area'>
  <h3>Search Stocks</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id = "friend-results">

</div>
<% if !@friends.blank? %>
  <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class='search-area'>
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id= "results" >

</div>
<% if !@tracked_stocks.blank? %>
<%= render 'stocks/list' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to the Finance Tracker </h1>
<p>Create a welcome page</p>