config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create,:destroy]
  resources :friendships, only: [:create,:destroy]
  devise_for :users
  get 'welcome/index'
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  get 'chart', to: 'stocks#chart'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  validates :name, :ticker, presence: true
  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
        publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
        endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      new(ticker: ticker_symbol,name:client.company(ticker_symbol).company_name,last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end
  def self.chart(ticker_symbol)
    client = IEX::Api::Client.new(
        publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
        endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      #new(ticker: ticker_symbol,name:client.company(ticker_symbol).company_name,last_price: client.price(ticker_symbol))
      client.chart(ticker_symbol)
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
 has_many :user_stocks
 has_many :stocks, through:  :user_stocks
 has_many :friendships
 has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def under_stock_limit?
	  stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
	  under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def stock_already_tracked?(ticker_symbol)
   stock = Stock.check_db(ticker_symbol)
   return false unless stock
   stocks.where(id: stock.id).exists?
  end
  def full_name
   return  "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end
 def self.search(param)
  param.strip!
  to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
  return nil unless to_send_back
  to_send_back
 end

 def self.first_name_matches(param)
  matches('first_name',param)
 end
 def self.last_name_matches(param)
  matches('last_name',param)
 end

 def self.email_matches(param)
  matches("email",param)
 end

 def self.matches(field_name, param)
  where("#{field_name} like ?", "%#{param}%")
 end

 def except_current_user(users)
  users.reject { |user| user.id == self.id }
 end

 def not_friends_with?(id_to_friend)
  !self.friends.where(id:id_to_friend).exists?
 end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @article = Article.new
  end
  def edit
    @article = Article.find(params[:id])
  end
  def show
    @article = Article.find(params[:id])
  end
  def index
    @articles = Article.all
  end
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  private
    def article_params
      params.require(:article).permit(:title,:text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
  private
  def comment_params
    params.require(:comment).permit(:commenter,:body)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |fm|
          fm.js {render partial: 'users/result'}
        end
      else
        flash.now[:alert] = "Please enter a valid symbol to search"
        respond_to do |fm|
          fm.js {render partial: 'users/result'}
        end
      end
    else
      flash.now[:alert] = "Please enter a symbol to search"
      respond_to do |fm|
        fm.js {render partial: 'users/result'}
      end
    end
  end
  def chart
    if params[:stock].present?
      @stock = Stock.chart(params[:stock])
      if @stock
        render json: @stock
      else
        flash[:alert] = "Please enter a valid symbol to search"
        redirect_to my_portfolio_path
      end
    else
      flash[:alert] = "Please enter a symbol to search"
      redirect_to my_portfolio_path
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
  end
  def my_friends
    @friends = current_user.friends
  end
  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |fm|
          fm.js {render partial: 'users/friend_result'}
        end
      else
        respond_to do |fm|
          flash.now[:alert] = "Couldn't find user"
          fm.js {render partial: 'users/friend_result'}
        end
      end
    else
      respond_to do |fm|
        flash.now[:alert] = "Please enter a friend to name or email to search"
        fm.js {render partial: 'users/friend_result'}
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th scope="col">Email</th>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <td><%= friend.email %></td>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td> <%= link_to 'Stop following', 'friendship_path(friend)',method: :delete, data: {confirm: 'Are you sure?'},
                                              class: 'btn btn-sm  btn-warning' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
        <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
        <%= alert %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'FinanceTracker', root_path, class: "navbar-brand" %>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
            <%= link_to 'My Portforlio', my_portfolio_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
            <%= link_to 'My Friends', my_friends_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to  edit_user_registration_path,class: 'dropdown-item' do %>
              <%= fa_icon 'edit' %>  Edit profile
              <% end %>

              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item  user-name">
            <%= fa_icon 'user' %> <%= current_user.full_name %>
          </li>
          <li class="nav-item">
            <%= link_to("Logout", destroy_user_session_path,
                        class: "btn btn-xs btn-danger logout-button", method: :delete) %>
          </li>
        </ul>

        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  </body>
</html>